### ISSUE TITLE
Figure out units of constant GAW

### ISSUE THREAD

**Issue by EmilSoleymani** [smiths/vdisp#58] opened 2022-05-17 20:48 UTC
The variable GAW, supposedly representing gamma_w, is said to be the unit weight of water. This constant is known to be 9.81kN/m^3 in SI Units. The book clearly states that it is 0.031tsf. Tsf is tonnes per square foot, and does not translate to N/m^3. In fact it is a unit of pressure, and translates to N/m^2 in SI Units. Find an explanation for this discrepancy in unit conversions.

**Comment by dstolle** [comment] 2022-05-30 18:34
GAW is 64.4 pcf or 9.81 kN/m^3

**Comment by dstolle** [comment] 2022-05-30 18:45
Yes, we can work with tcf

**Comment by smiths** [comment] 2022-05-30 18:48
Great!  With the question answered, we can now close this issue.

**Closed by smiths** 2022-05-30 18:48 UTC
Labels: help wanted

**Comment by dstolle** [comment] 2022-05-30 19:06
PS:  The problem is likely with respect to conversion factors. I just pulled my Bowles from the shelf. He indicates that  1000 pcf = 157.087 kN/m^3.  I made a typo, GAW = 62.4 pcf.

**Comment by smiths** [comment] 2022-05-30 19:08
62.4/2000 is 0.0312, which rounds to the 0.031 used in the code.  The good news is that the number in the code is correct.  It was just an issue with the units used in their documentation.
